"""add created_by and updated_by tracking to users

Revision ID: 7fb0f06463a3
Revises: f1f43cb499ad
Create Date: 2026-09-21 16:44:40.707337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb0f06463a3'
down_revision: Union[str, None] = 'f1f43cb499ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_created_by_id'), 'users', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_users_updated_by_id'), 'users', ['updated_by_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_created_by_id_users'), 'users', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_users_updated_by_id_users'), 'users', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_updated_by_id_users'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_created_by_id_users'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_updated_by_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_by_id'), table_name='users')
    op.drop_column('users', 'updated_by_id')
    op.drop_column('users', 'created_by_id')
    # ### end Alembic commands ###